# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_auto_20160415_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lunchgate_id',
            new_name='facebook_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
