# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20160502_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='facebook_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
