# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20160503_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='facebook_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
